### ISSUE TITLE
AdBlock Lean - Unsupported Configuration  after update of AdBlock Lean 

### ISSUE THREAD

**Issue by kondakos** [rickparrish/luci-app-adblock-lean#2]
Hi,

After   update of AdBlock Lean  the [Overview](https://*.*.*.1/cgi-bin/luci/admin/services/adblock-lean/overview) there is a message. 

![image](https://github.com/user-attachments/assets/8db4f0c2-1378-410d-a7a2-5d6df6ea030d)

AdBlock Lean - Status
Service Status	AdBlock Lean will autostart on boot
Blocklist Status	Blocklist is active. Good line count: 100,450. Last updated 0 hour(s) ago.
dnsmasq Status	dnsmasq is running
AdBlock Lean Update Status	Up to date
LuCI App Update Status	Up to date

AdBlock Lean - Unsupported Configuration 
 

The currently installed versions of adblock-lean and luci-app-adblock-lean are not compatable with each other (they do not support the same config format).

Check the status panel above to see whether there are updates for one (or both) packages, and update as necessary.

NOTE: adblock-lean will continue to function as expected while this incompatability exists, the only functionality you are missing out on is the configuration form.
luci-app-adblock-lean | git-24.263.74250-a8b02d0 |

**Comment by rickparrish** [comment]
Thanks for the heads up, I didn't notice that adblock-lean was updated the other day.  I should have time to update the luci app later this evening.

**Comment by rickparrish** [comment]
Just built a new package, so if you reload you should see a "Update LuCI App" button now.

The page didn't work for me afterwards, I had to manually issue a `service rpcd reload` via SSH to get things working again.  Probably because that's definitely not the standard way to update a LuCI app.

**Comment by kondakos** [comment]
Thank you. The issue fixed.
